package org.connectpwd.common;

public enum ErrorCode {
    VALIDATION_ERROR,
    AUTHENTICATION_FAILED,
    TOKEN_EXPIRED,
    TOKEN_INVALID,
    ACCESS_DENIED,
    DUPLICATE_EMAIL,
    USER_NOT_FOUND,
    CONSENT_NOT_FOUND,
    CONSENT_NOT_AGREED,
    SESSION_NOT_FOUND,
    SESSION_ACCESS_DENIED,
    SESSION_ALREADY_COMPLETED,
    QUESTION_NOT_FOUND,
    ANSWER_ALREADY_EXISTS,
    SCORING_NOT_READY,
    SCORE_NOT_FOUND,
    REPORT_NOT_FOUND,
    REPORT_GENERATION_FAILED,
    STORAGE_ERROR,
    RATE_LIMIT_EXCEEDED,
    INTERNAL_ERROR
}
